__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/custom10.yml',  # FPN-PAN to PAN,num_decoder_layers has changed from 6 to 4
]

YOLOBackbone:
  # add SPD Conv,use v7 backbone
  cfg: 'configs/rtdetr/include/custom10_backbone.yml'

train_dataloader:
  batch_size: 8
  num_workers: 4

use_amp: False
epoches: 200


optimizer:
  params:
    - params: 'backbone'
      lr: 0.00001
  lr: 0.0001

output_dir: ./output/custom11